# Generated by Django 2.0.6 on 2018-06-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20180629_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-create_at']},
        ),
    ]
